<?php declare(strict_types=1); $docsUrl=new App\DocsService();$endpoint=rtrim(App\Config::get('APP_URL',''),'/').'/api/'.$connector['slug']; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($connector['name'])?> API documentation</title><link rel="stylesheet" href="/assets/styles.css"></head>
<body><header class="topbar"><div><div class="eyebrow">Universal AI API Connector</div><h1><?=htmlspecialchars($connector['name'])?></h1></div><a class="btn secondary" href="/">Back to API Hub</a></header>
<main class="page narrow"><section class="card prose"><div class="pill-row"><span class="pill"><?=htmlspecialchars($connector['provider'])?></span><span class="pill"><?=htmlspecialchars($connector['model'])?></span><span class="pill"><?=((int)$connector['is_active']===1?'Active':'Disabled')?></span></div>
<p><?=nl2br(htmlspecialchars($connector['description']))?></p><h2>Endpoint</h2><code>POST <?=htmlspecialchars($endpoint)?></code>
<h2>Authentication</h2><p>Send the connector API key using <code>X-API-Key</code> or <code>Authorization: Bearer</code>. Provider credentials are server-side only.</p>
<h2>Input parameters</h2><div class="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th><th>Validation/default</th></tr></thead><tbody><?php foreach($connector['input_schema'] as $f): ?><tr><td><code><?=htmlspecialchars($f['name'])?></code></td><td><?=htmlspecialchars($f['type'])?></td><td><?=($f['required']??false)?'Yes':'No'?></td><td><?=htmlspecialchars($f['description']??'')?></td><td><?=htmlspecialchars(json_encode(array_intersect_key($f,array_flip(['default','min','max','max_length','enum','max_size'])),JSON_UNESCAPED_SLASHES))?></td></tr><?php endforeach ?></tbody></table></div>
<h2>Request example</h2><pre class="response-box"><?=htmlspecialchars(json_encode($docsUrl->examplePayload($connector),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre>
<h2>cURL</h2><pre class="response-box"><?=htmlspecialchars($docsUrl->curl($connector))?></pre>
<h2>Expected response</h2><pre class="response-box"><?=htmlspecialchars(json_encode(['success'=>true,'data'=>$connector['output_schema'],'error'=>null,'meta'=>['request_id'=>'req_...','response_time_ms'=>842,'provider'=>$connector['provider'],'model'=>$connector['model']]],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre>
<h2>Error response</h2><pre class="response-box"><?=htmlspecialchars(json_encode(['success'=>false,'data'=>null,'error'=>['type'=>'validation_error','message'=>'Invalid input.'],'meta'=>['request_id'=>'req_...']],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre>
<h2>Output schema</h2><pre class="response-box"><?=htmlspecialchars(json_encode($connector['output_schema'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre>
</section></main></body></html>
